subfolder proxying
ItsEcholot/ContainerNursery pull request #43
Opened 2023-04-21 01:57 UTC by everythingguy

Resolves https://github.com/ItsEcholot/ContainerNursery/issues/27 

One important note, the application you are proxying would need to be able to rewrite its URLs to include the subfolder at the beginning of its URLs.

2023-04-21 02:00 UTC, everythingguy commented
Example Config

```yaml
proxyListeningPort: 80
proxyHosts:
  - domain: test.com/myapp
    containerName: hello-world
    proxyHost: localhost
    proxyPort: 3000
    timeoutSeconds: 120
```

2023-07-18 23:42 UTC, webysther commented
I have a case the use example.com and example.com/admin, which point to different container/port, this PR works for this scenario?

2023-07-21 11:02 UTC, ItsEcholot requested changes

2023-07-21 11:02 UTC, ItsEcholot commented on src/index.ts
> +
This code section seems brittle. Please use the [URL API](https://developer.mozilla.org/en-US/docs/Web/API/URL_API) to get parts of urls.

2023-07-21 11:02 UTC, ItsEcholot commented on src/index.ts
> +
Same as above and please avoid duplicate code where possible

2026-01-14 11:47 UTC, ItsEcholot commented
@everythingguy I'm going to close this as stale. Let me know if you want to continue working on this and I can reopen.

2026-01-14 11:47 UTC, closed without merging